### ISSUE TITLE
Create & Attach Storage

### ISSUE THREAD

**Issue by sdrose** [niwo/cloudstack-cli#10]
Hello Nik!
I know you're away for a few days, but I wanted to notify you as to what I believe is a bug I see in version 1.2.7.  I am trying to create a volume, but it does not attach automatically.

PS C:\Users\606457840\DevKit> cs volume create DATA-srvtlkdb01 --disk-offering=Custom --virtual-machine=srvtlkdb01 --zone=US-NEW-NUT-G-V-A-R-S-001 --size=1300
Creating volume DATA-srvtlkdb01 . OK.
No volume with name "DATA-srvtlkdb01" found.
PS C:\Users\606457840\DevKit> cs volume attach DATA-srvtlkdb01 --virtual-machine=srvtlkdb01
Attach volume DATA-srvtlkdb01 to VM srvtlkdb01 ............... OK.
PS C:\Users\606457840\DevKit>

However, after manually attaching, it seems fine.

-dave

**Comment by niwo** [comment]
Hi Dave,

That was the expected behavior from the createVolume API command.
I now added an additional attachVolume call if a vm name is given. 
Improved in f553bcb2f86783afe7720f781c969c12ba799f22 (v1.3.0).

Nik
