### ISSUE TITLE
Volume.rb file

### ISSUE THREAD

**Issue by sdrose** [niwo/cloudstack-cli#11]
Line #93 is incorrect (only a description though ... )
reads:
option :virtual_machine, desc: 'project of volume'

should be:
option :virtual_machine, desc: 'virtual machine of volume'

However, the creation of the volume does not attach the volume to the specified --virtual-macine

-dave

**Comment by niwo** [comment]
Hi Dave,

Fixed in f553bcb2f86783afe7720f781c969c12ba799f22 (v1.3.0).
Thanks for reporting!

Nik
