### ISSUE TITLE
can't 'cs network list'

### ISSUE THREAD

**Issue by sdrose** [niwo/cloudstack-cli#14]
crash with 'cs network list' with the new version 1.5.2

C:\Users\606457840>cs network list
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/cloudstack_client-1.4.0/lib/cloudstack_client/connection.rb:51:in `digest': no implicit conversion of nil into
String (TypeError)
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/cloudstack_client-1.4.0/lib/cloudstack_client/connection.rb:51:in `send_request'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/cloudstack_client-1.4.0/lib/cloudstack_client/client.rb:38:in `block (2 levels) in define_api_meth
ods'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/cloudstack-cli-1.5.2/lib/cloudstack-cli/commands/network.rb:17:in `list'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:235:in `block in subcommand'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/cloudstack-cli-1.5.2/lib/cloudstack-cli/base.rb:17:in `start'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/cloudstack-cli-1.4.1/bin/cs:5:in `<top (required)>'
        from C:/Ruby22-x64/bin/cs:22:in `load'
        from C:/Ruby22-x64/bin/cs:22:in `<main>'

C:\Users\606457840>

**Comment by niwo** [comment]
Hi Dave,

This looks strange - but I'm not able to re-produce it in my environment.

Does any command run in your environment?  
Do you have a valid environment config (url, api_key, secret_key)?

Thanks,
Nik

**Comment by niwo** [comment]
Hi Dave,

I just checked: This error appears when the secret_key within the environment has no value (nil):

```yaml
:url: https://cloudstack.io/client/api/
:api_key: 8u87837892318798390810381083081038018301830
:secret_key:
```

Can you please check your environment file?

Thanks,
Nik

**Comment by sdrose** [comment]
Hello Nik
So, what it was -- I had a blank entry -- Not set as my current, or Default environment.  But, after deleting this blank entry completely, and re-setting the default environment, Cloudstack-cli is working well now.

So sorry I had the incorrect setting in my config file ...

-dave

**Comment by niwo** [comment]
No problem. I should add some better error handling for such cases
