### ISSUE TITLE
string matching

### ISSUE THREAD

**Issue by sdrose** [niwo/cloudstack-cli#15]
So an annoying bug I have discovered is with string / pattern matching.  Take the below example, where I have 2 similarly-named VMs.

Daves-Mac:~ drose$ cs server list | grep -i tgifps
TGIFPSTEMPLATEBUILD   Stopped  4vCPU-2660MHz-8GB-RAM    
TGIFPS1201            Running  2vCPU-2660MHz-8GB-RAM        
TgifPs1201-srv2       Running  2vCPU-2660MHz-8GB-RAM         

Daves-Mac:~ drose$ cs server show tgifps1201
id:                     e3967526-efc8-4f43-8f45-5b54c12031c3
name:                   TgifPs1201-srv2
displayname:            TgifPs1201-srv2

Note I have 2 servers with the left-matching characters, 'tgifps1201'
When I request information from the 1st (TGIFPS1201), I am actually presented with information from the 2nd (TgifPs1201-srv2).

-dave

**Comment by niwo** [comment]
Hi Dave,

Thanks for reporting this nasty bug!
Fixed in v1.5.3 88f5314d97d6a57240e992acfa3798e591f2f403 

Kind regards,
Nik
