### ISSUE TITLE
cs command with resolution

### ISSUE THREAD

**Issue by sdrose** [niwo/cloudstack-cli#16]
So, This is strictly a feature-request that I think would make your software totally awesome .....

Is there a methodology where you could invoke 'resolution' in the cs command?

So, let me illustrate with examples.

Say I have a server -- cloudsrv1, and a network -- cloudnet1

I might want to do a one-off API command that you don't have 'baked' into a Cloudstack-cli commmand -- very infrequently -- such as:

addNicToVirtualMachine

I would have to look up 2 of the required arguments, networkid and virtualmachineid.  And I might have to add a third, ipaddress.

What I am proposing as a new feature is, for instance, a lookup character -- maybe %.

So, I would propose is this functionality:

cs command addNicToVirtualMachine networkid=%cloudnet1(id) virtualmachineid=%cloudsrv1(id) ipaddress='192.168.1.2'

So, %cloudnet1(id) might resolve back as 814b67a0-60ab-4dbb-820d-a3cf26c5d28d  
(field 'id' from cs networks show cloudnet1)

And, same with %cloudsrv1(id) might resolve back as 032c9604-090e-4042-a5e0-920e842d6ca2
(field 'id' from cs server show cloudsrv1)

You have added so many useful commands (cs networks, cs server, cs_ipaddress, etc) and a great catch-all with the cs command.  I think having built-in resolution as part of the cs command would be a killer feature.

As always, thank you for what you have written and made available in Open Source.  You have a wonderful software package here.  I hope you don't tire from my feature suggestions and bug reports, as I've had many over the past several months ....

Respectfully,
-dave
BT Advise, US&C

**Comment by niwo** [comment]
Yes, this would be definitively a cool feature.
At the moment I don't see a elegant way on how to implement this - let me think about this some time...

**Comment by sdrose** [comment]
Hello Nik!
I very much believe in your cloudstack client software.  Given my desire to help on this, I wanted to see if you think this would be a help for you ....?

I have hacked together a quick function, called resolve, in order to test the line I have created.  Please forgive my crude scripting, I have only been testing within irb, and am brand-new to Ruby.  

Since you have already done the work which resolves certain fields from 'objects' -- and by object, I mean a volume object within Cloudstack, or a VM object.  These objects have fields within them, such as a diskofferingid field, or just an id field.   This obviously does 2 things .. shows the names of the strings I have passed in as csObject adn csField, and returns a 26-characted string with a dash every 8 characters, to SIMULATE an ID field.

def resolve(csObject, csField)
      puts "object: #{csObject} field: #{csField}"
      return (0...26).map { (65 + rand(26)).chr }.join.gsub(/(.{8})(?=.)/, '\1-\2')
end

Thinking about the requirement for my ask, really, I think we only need to modify the library for CS COMMAND.  There is no need to have a 'global' resolver, just within Cloudstack Command because that is the catch-all.  This is where is needed to resolve an ID field from any CloudStack object.

So, with the idea of the following statement:
resizeVolume diskofferingid=@@(data-vol1,diskofferingid) volumeid=@@(data-vol2,storageid)

I wanted to identify the pattern Cloudstack-API-Field=@@(name-of-Cloudstack-object, field-within-the-Cloudstack-object) and have the right-side of the equal symbol be replaced by the Cloudstack ID value.

Here is the line I think can be added to the library for Cloudstack Command.
string.gsub(/@@\(([^)]+)\)/) { |m| "#{resolve(m.gsub(/[()@]/,"").gsub(/[@@]/,"").split(',')[0], m.gsub(/[()@]/,"").gsub(/[@@]/,"").split(',')[1])}" }

This is not the model for elegance, to be sure!
Anyway, whatever string within CS Command which originally holds the ARGV captured from the shell would be modified by this regex GSUB.

Here is how I have tested....
irb(main):044:0* 'command resizeVolume diskofferingid=@@(data-vol1,diskofferingid) volumeid=@@(data-vol2,storageid) size=125'.gsub(/@@\(([^)]+)\)/) { | m | "#{resolve(m.gsub(/[()@]/,"").split(',')[0], m.gsub(/[()@]/,"").split(',')[1])}" } 
object: data-vol1 field: diskofferingid
object: data-vol2 field: storageid
=> "command resizeVolume diskofferingid=MJQGRMSJ-RRNXAHFT-DJLULWNC-EK volumeid=DASKLIYE-SKTCNUDY-SLAVUBID-EL size=125"


Of course, this is predicated upon the idea that you could wrap your existing id-resolution code into a function (or similar construct) based on the 2 elements I have identified in the regex.

I hope this is helpful to you!  Apologies if it is not.

-dave

**Comment by sdrose** [comment]
Hello Nik.
So, I'm struggling a little bit here, but let me throw out a suggestion please.  Looking in OptionResolver, you already have the following list:
resolve_zone
resolve_project
resolve_compute_offering
resolve_template
resolve_disk_offering
Resolve_iso_for_VM_deployment
resolve_domain
resolve_acount
resolve_networks
resolve_IP_network_list
resolve_iso
resolve_virtual_machine
resolve_snapshot
resolve_host

ANd, in cloudstack-cli/lib/cloudstack-cli/cli.rb, you have the 'command'.
params = {'command'=>command}
args.each do |arg|
    arg = arg.split('=')
    Params[arg[0]]=arg[1]
end.

Could it be reasonably elegant to then split the arg1 going into the params statement to list the resolution module?  
So, I mean .. if I wanted to resolve a the ID of a named Volume, you've got the heavy lifting already done.  Could we do the following:
    cs command createSnapshot volumeid=resolve_volume:ROOT_12345 account=resolve_account:compute01@bt.com quiescevm='true'

and from the arg1 (resolve_volume:ROOT_12345) split it on the ':', use the first half as the resolve module, and the second half as the name to resolve?

Thank you for listening to my continued harassment on this topic!
-dave

**Comment by niwo** [comment]
Hi Dave,

Unfortunately I didn't have the time to work on this.

What makes it rather complex and time consuming, is the fact that most of the commands depend on IDs of other entities (like the zone_id, account_id, project_id etc.).
This makes it hard to implement a generic resolver which works for all the commands.

Probably it would be feasible to implement a "interactive" mode which ask about the params and presents a list of possible options in the right order (similar to `cloudstack-cli vm create-interactive`).

Kind regards,
Nik

**Comment by sdrose** [comment]
Just as glue until this can be properly integrated, I have begun with small helper scripts for name/id resolution.

In BASH I echo a command line to resolve the name. Since I only just wrote the resolve script a couple days ago, I echo the command rather than implement it because I want to verify proper resolution.

For example, here is a command I entered to resolve the names in the command:

    drose$ echo "cs command addNicToVirtualMachine networkid='$(./cs_netID.sh Backup-Dev)' virtualmachineid='$(./cs_serverID.sh dvusntywks01)' ipaddress='10.112.20.191'"

which yields the following (to be copied and pasted on the BASH commandline):

    cs command addNicToVirtualMachine networkid='11a9008f-721d-4b79-b7bf-72bad6c53168' virtualmachineid='ba5526bd-7fc3-41cd-9da2-2f9cb4e5f859' ipaddress='10.112.20.191'

Since this refers on 2 helper scripts, they are here.  Place them in the current path please:

cs_netID.sh:

    #!/bin/bash

    networkName="$1"
    cs network show $networkName | grep -i "^id:" | awk -F':' '/:/{gsub(/ /, "", $0); print $2} ' 

cs_serverID.sh:

    #!/bin/bash

    serverName="$1"
    cs server show $serverName | grep -i "^id:" | awk -F':' '/:/{gsub(/ /, "", $0); print $2} ' 

I guess, maybe a better way would be to echo this command and redirect it to a script file ( as in appending > addNic.sh ) so you don't have to copy, paste and execture but rather run, and then run the created script.  Anyway, it was just some 'script glue' I created so I don't have to keep looking up IDs manually.
