### ISSUE TITLE
cloudstack-cli offering sort from Code-Page Documentation ...

### ISSUE THREAD

**Issue by sdrose** [niwo/cloudstack-cli#17]
Wanted to check the sorting of compute offerings as you list in the 'home-page' documentation, and I received the following errors.  I think, first, you meant to say, 'Cloudstack-cli compute-offer sort'.  And when I try the sort on Cloudstack-cli compute_offer sort, I receive an error after the first is displayed.  

Daves-Mac:~ drose$ cloudstack-cli offering sort
Could not find command "offering".

Daves-Mac:~ drose$ cloudstack-cli compute_offer sort
1  - 1vCPU-500MHz-1GB-RAM
ERROR: ApiError - Status 500: The given command:updateServiceOffering does not exist or it is not available for user with id:null.
Daves-Mac:~ drose$ 

Thanks!
-dave

**Comment by niwo** [comment]
Hi Dave,

Yes, your right the name of the command is "compute_offer" and not "offering" from some time now.
Also you require root admin privileges to run this command.

I corrected the section in the README and added a note about privileges.

Thanks,
Nik
