### ISSUE TITLE
Query on command to put host into maintenance mode

### ISSUE THREAD

**Issue by wingZero21** [niwo/cloudstack-cli#19]
Hi,

Do you know if there is a command available to put a host into maintenance mode.

Cheers
Mark

**Comment by niwo** [comment]
Hi Mark,

There is no "special" cloudstack-cli command for this but you can do it using the native API command "updateHost" like this:

```bash
cloudstack-cli command updateHost id=<host-id> allocationstate=Disable
```

You can find the host-id for the command above using `cloudstack-cli host list --format json`

Cheers,
Nik
