### ISSUE TITLE
Provide cluster level capacity information

### ISSUE THREAD

**Issue by wingZero21** [niwo/cloudstack-cli#21]
Hi,

This is more of a feature request than a problem.

Currently we can get the information by running a custom command detailed below, however it would be great as part of the existing capacity view if we could get this on a per cluster basis similar to how we can get it for the zone.

Cheers
Mark

EG:
Current command to get Cluster information
```
cloudstack-cli command listCapacity clusterid=CLUSTER ID HERE type=0
```

Current command to get zone information
```
cloudstack-cli capacity list --zone=ZONE --type=0
```

**Comment by niwo** [comment]
Hi,

[cloudstack-cli 1.5.7](https://github.com/niwo/cloudstack-cli/releases/tag/v1.5.7) now supports this feature:

```bash
cloudstack-cli capacity list --cluster cluster-a
```

Cheers,
Nik
