### ISSUE TITLE
Error displaying self-owned templates

### ISSUE THREAD

**Issue by sdrose** [niwo/cloudstack-cli#22]
$ cloudstack-cli --version
cloudstack-cli version 1.6.3
 (cloudstack_client version 1.5.4)

$ cloudstack-cli  template  list --zone=US-NEW-NUT-G-V-A-R-S-001  --type=self
Traceback (most recent call last):
	17: from /usr/local/bin/cloudstack-cli:23:in `<main>'
	16: from /usr/local/bin/cloudstack-cli:23:in `load'
	15: from /home/drose/.gem/ruby/gems/cloudstack-cli-1.6.3/bin/cloudstack-cli:5:in `<top (required)>'
	14: from /home/drose/.gem/ruby/gems/cloudstack-cli-1.6.3/lib/cloudstack-cli/base.rb:17:in `start'
	13: from /usr/local/share/gems/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	12: from /usr/local/share/gems/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	11: from /usr/local/share/gems/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	10: from /usr/local/share/gems/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	 9: from /usr/local/share/gems/gems/thor-0.20.0/lib/thor.rb:238:in `block in subcommand'
	 8: from /usr/local/share/gems/gems/thor-0.20.0/lib/thor/invocation.rb:115:in `invoke'
	 7: from /usr/local/share/gems/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	 6: from /usr/local/share/gems/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	 5: from /usr/local/share/gems/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	 4: from /home/drose/.gem/ruby/gems/cloudstack-cli-1.6.3/lib/cloudstack-cli/commands/template.rb:26:in `list'
	 3: from /home/drose/.gem/ruby/gems/cloudstack-cli-1.6.3/lib/cloudstack-cli/commands/template.rb:26:in `each'
	 2: from /home/drose/.gem/ruby/gems/cloudstack-cli-1.6.3/lib/cloudstack-cli/commands/template.rb:29:in `block in list'
	 1: from /usr/share/ruby/time.rb:367:in `parse'
/usr/share/ruby/time.rb:367:in `_parse': no implicit conversion of nil into String (TypeError)

**Comment by niwo** [comment]
1.6.4 should rescue the exception and continue when there is a template which has no "created" value set
