### ISSUE TITLE
Question re: provision with .ISO

### ISSUE THREAD

**Issue by sdrose** [niwo/cloudstack-cli#6]
Hello.
I don't know where to access a mail list, and this could just be my not properly understanding the syntax of the cloudstack-cli.  However, I was hoping you could point me to what I'm doing wrong.  My problem is when trying to create a vm via the CLI, I receive the error, "Error:  a disk offering is required when using iso."  However, I believe I am correctly supplying the Custom disk offering, and its disk size.  Here is my syntax:
 
C:\Users\user>cs virtual_machine create ApiTest --offering=1vCPU-1500Mhz-2GB-RAM --zone=US-NEW-NUT-G-V-A-R-S-001 --Networks=Envr_Prod1_VLAN2 --hypervisor=Vmware --iso=PlatesponBoot_W2K8R2 --disk-offering=Custom --disk-size=85
Error: a disk offering is required when using iso.
 
 
Reference info:
C:\Users\user>cs iso list
Name                             Zone                      Bootable  Public  Fea
tured
windows_server_2008_r2_with_sp1  US-NEW-NUT-G-V-A-R-S-001  true      false   false
PlatesponBoot_W2K8R2             US-NEW-NUT-G-V-A-R-S-001  true      false   false
Total number of isos: 2
 
C:\Users\user>cs disk_offer list
Name           Displaytext               Domain  ID
Small 1        Small Disk, 5 GB                  685a86ae-bf7a-4aa4-bc44-243454967073
Small 2        Small Disk, 20 GB                 e959d785-b485-4906-be51-d1f4cbfe8395
Medium 1       Medium Disk, 80 GB                479955e4-4d03-46e5-b9fb-34f40ff8d0bb
Medium 2       Medium Disk, 100 GB               961b6141-2d30-411a-a7a1-8650b7fbaed5
Medium 3       Medium Disk, 300 GB               948e044f-1ad2-42b7-8269-84d781b952f6
Large 1        Large Disk, 1 TB                  c509fd22-1f7e-4449-b8f3-66162a9e6c59
Large 2        Large Disk, 1.5 TB                b0f2fb6c-6f0a-492f-bb96-9255c27e7229
Extra Large 1  Extra Large Disk, 2 TB            c5c0378a-20e4-458a-9ace-5adc0a484d83
Custom         Custom Disk (Max 500 GB)          ca388608-706d-4a42-903d-da004276b5bb
Small3         Small Disk, 30GB                  74b319c8-8a9c-444f-b25c-ba87c2e2a60a
Total number of offerings: 10
 
C:\Users\user>cs network list
Name                Displaytext         Account/Project                       Zone                      Domain                       State        Type      Offering
Envr_BUILD_NETWORK  Envr_BUILD_NETWORK  BT_Cloud_Compute_USD_Envrusra@bt.com  US-NEW-NUT-G-V-A-R-S-001  1182950434-Envr Implemented  Isolated  defaultIsolatedNetworkOfferingWithSourceNatService
Envr_PROD1_VLAN2    Envr_PROD1_VLAN2                                          US-NEW-NUT-G-V-A-R-S-001  1182950434-Envr  Setup        Shared    DefaultSharedNetworkOffering
Total number of networks: 2
 
Thank you for any assistance you can provide!!!
-Dave

**Comment by niwo** [comment]
Hi Dave,

Your are completely right: This should work.
I checked and there was actually a bug in the options resolver code which checked the wrong option to be set (:diskoffering_id instead of :disk_offering_id).

It fixed it and released a new version of the gem (v1.2.4).


Thanks for pointing this out!

Nik

**Comment by sdrose** [comment]
Thank you, Nik!!!!
I thought i was losing my mind!!  

I am running a test right now, and I can see that the new v.1.2.4 is working to deploy a machine.  Let me please ask a question … I want to deploy a machine and specify the IP address that should be put in as the DHCP reservation.  Also, I want to deploy VMs with a second IP address for the 1 NIC.  The system architect I am working with has seen it is possible to set a second IP address on the 1 NIC — What would I add to the command line to specify the IP addresses during the creation phase?  Would that be part of the —networks argument?

-dave

**Comment by sdrose** [comment]
Plus, I believe your 'usage' text from cs virtual_machine create is incorrect.  
It says:
iMac:~ drose$ cs virtual_machine help create
Usage:
  cs create NAME [NAME2 ...] -o, --offering=OFFERING -z, --zone=ZONE

where I believe you intended for it to say:
iMac:~ drose$ cs virtual_machine help create
Usage:
  cs virtual_machines create NAME [NAME2 ...] -o, --offering=OFFERING -z, --zone=ZONE

And I think there is another error.  Please see this:
iMac:~ drose$ cs virtual_machine create "TestFromAPI" --offering=1vCPU-1500Mhz-2GB-RAM --zone=US-NEW-NUT-G-V-A-R-S-001 --networks=Envr_PROD1_VLAN2  --iso="PlatesponBoot_W2K8R2" --disk-offering=Custom --disk-size=82 
Start deploying virtual machine...
Create virtual machine TestFromAPI : job completed 
Completed: 1/1 (204.8s)
Finished.
iMac:~ drose$ cs server list
Name                                     State    Offering               Zone                      Account                               IP's
VM-c346be3c-b6f2-4e0a-9bb4-f7cc7b8f496c  Running  1vCPU-1500Mhz-2GB-RAM  US-NEW-NUT-G-V-A-R-S-001  Cloud_Compute_USD_envrusra@me.com  10.71.2.7
TestFromPortal                           Running  2vCPU-2660MHz-8GB-RAM  US-NEW-NUT-G-V-A-R-S-001  Cloud_Compute_USD_envrusra@me.com  10.71.2.89 10.50.2.207
VM-58d91089-f27d-4f2b-9bcc-1b6d43c5a2fb  Running  1vCPU-1500Mhz-2GB-RAM  US-NEW-NUT-G-V-A-R-S-001  Cloud_Compute_USD_envrusra@me.com  10.71.2.118

You'll see there are 2 VMs with incorrect names.  The VMs I tried to create as TestFromAPI and also previously as APITest have the randomly-generated names.  This seems to be an error, as I would expect the VM to have APITest and TestFromAPI. rather than VM-58d91089-f27d-4f2b-9bcc-1b6d43c5a2fb &  VM-c346be3c-b6f2-4e0a-9bb4-f7cc7b8f496c

Also, can I add the following information in the provision command?
"netmask"=>"255.255.255.0" 
"gateway"=>"10.71.2.1" 
"ipaddress"=>"10.71.2.118" 
"isdefault"=>true,

**Comment by sdrose** [comment]
Also, I see errors in the attempt to destroy a VM.   I am using 1.2.3 as the Client and 1.2.4 as the CLI.

iMac:~ drose$ cs server stop "VM-c346be3c-b6f2-4e0a-9bb4-f7cc7b8f496c"
Stop virtual machine VM-c346be3c-b6f2-4e0a-9bb4-f7cc7b8f496c? [y/N]: y
.....
iMac:~ drose$ cs server destroy "VM-c346be3c-b6f2-4e0a-9bb4-f7cc7b8f496c"
/usr/local/lib/ruby/gems/2.3.0/gems/cloudstack-cli-1.2.4/lib/cloudstack-cli/commands/virtual_machine.rb:136:in `block in destroy': undefined local variable or method `machine' for #<VirtualMachine:0x007fc47b96d790> (NameError)
	from /usr/local/lib/ruby/gems/2.3.0/gems/cloudstack-cli-1.2.4/lib/cloudstack-cli/commands/virtual_machine.rb:132:in `each'
	from /usr/local/lib/ruby/gems/2.3.0/gems/cloudstack-cli-1.2.4/lib/cloudstack-cli/commands/virtual_machine.rb:132:in `destroy'
	from /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
	from /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:235:in `block in subcommand'
	from /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /usr/local/lib/ruby/gems/2.3.0/gems/cloudstack-cli-1.2.4/lib/cloudstack-cli/base.rb:15:in `start'
	from /usr/local/lib/ruby/gems/2.3.0/gems/cloudstack-cli-1.2.4/bin/cs:5:in `<top (required)>'
	from /usr/local/bin/cs:23:in `load'
	from /usr/local/bin/cs:23:in `<main>'
iMac:~ drose$

**Comment by niwo** [comment]
Hi Dave

**help text for subcommands**
That's an issue with thor (the cli parser lib I'm using).
I added a monkey patch to the v1.2.5 in order to fix it.

**advanced options like secondary IP's in vm create**
Add the time being cloudstack-cli does not support all advanced options for the implemented commands.
But take a look at `cloudstack-cli command ...` - like this you can access the "raw" CloudStack API and use all options which are supported, see:
 - https://cloudstack.apache.org/api/apidocs-4.8/root_admin/deployVirtualMachine.html
 - https://cloudstack.apache.org/api/apidocs-4.8/root_admin/addIpToNic.html

**VM names not set**
This happens if you provide unsupported hostnames. CloudStack is picky about that and does not support anything beside lower case letters, numbers and hyphens.
This can be confusing as the name is just ignored and then generated by CloudStack.

**Error in destroy command**
That was a nasty bug - fixed!

Thanks,
Nik

**Comment by sdrose** [comment]
Thank you so much, again, Nik!  
I will download the v 1.2.5 and try it momentarily.

So, just to make sure I understand.  Names have to be in all lower case to work.   The Destroy bug is fixed.  

I asked about secondary IP addresses, and you pointed me to the RAW apis.  Which I can do.  However, can I specify an initial IP address with your Create command then add the secondary addresses with the raw API?  Or, do I have to create a VM with your methodology, and then go back and specify the primary and secondary IP address via the raw API?

Thank you!
-dave

**Comment by sdrose** [comment]
Just tried twice creating VMs with a name -- all lower case letters, numbers, hyphens.  Naming did not work. The VMs show up as VM-8d8173f3-d2f3-4b68-8d06-94b126725351, and another in similar fashion, as name.

**Comment by niwo** [comment]
"cloudstack-cli vm create" does not support the configuration of a secondary IP.
Also it does not support choosing a specific IP in the DHCP range - honestly I'm not sure this is possible through the raw API (and I don't really see the use case, as DHCP takes care about it just fine).

The "strange" names you get  are the ones auto-generated by CloudStack (the name parameter is optional).
Can you give me an example of a vm-name which does not work for you?

**Comment by sdrose** [comment]
iMac:~ drose$ cs virtual_machine create testfromapi --offering=1vCPU-1500Mhz-2GB-RAM --zone=US-NEW-NUT-G-V-A-R-S-001 --networks=ENVR_PROD1_VLAN2  --iso="PlatesponBoot_W2K8R2" --disk-offering=Custom --disk-size=83
Start deploying virtual machine...
Create virtual machine testfromapi : job completed 
Completed: 1/1 (78.4s)
Finished.

Name                                     State    Offering               Zone                      Account                               IP's
VM-01648b43-1b07-4199-9819-b046a528543d  Running  1vCPU-1500Mhz-2GB-RAM  US-NEW-NUT-G-V-A-R-S-001  XX_Cloud_Compute_USD_yyyyusra@xx.com  10.71.2.211

**Comment by sdrose** [comment]
Do you think this would allow for setting the default IP address in the Apache CloudStack deployVirtualMachine API?

ipaddress        the ip address for default vm's network          false

The reason it would be helpful is I am planning out 80-90 VMs to deploy.  Having such an intricate plan requires me to have IP addresses planned so I can work with other groups, and we can approach this data center to cloud migration with all the work up-front.

This allows us to know what VM gets what IP address, and multiple teams can work in tandem until the actual deployment.

If we didn't do this, then I have to deploy all the VMs, record their IPs as assigned by DHCP, then bring that list of IPs to my networking co-workers to then begin planning firewall ACLs, load-balancing and such.

I appreciate all your efforts today!!!!  Thank you for your help in this endeavor!
-dave
Connecticut, USA.

**Comment by niwo** [comment]
Hi Dave,

1. I just verified: The "ipaddress" API option is doing what you want. I added a "--ip-address" option to vm create as well (v1.2.6)
2. You have been right - there was an issue with setting the vm name in my code. Sorry about that. Fixed.

Cheers,
Nik
