### ISSUE TITLE
Feature Request ...

### ISSUE THREAD

**Issue by sdrose** [niwo/cloudstack-cli#8]
Hello Nik!
You have such an awesome piece of software here, that I thought this feature would be just AMAZING.  
If you add, utilizing the updateVirtualMachine api call:
  cs virtual_machines update [EXISTING KEY/VALUE] [UPDATE KEY/VALUE]

Use cases in my mind ... update a VM name, update the established IP address, etc.  To be able to reap the benefits of the updateVirtualMachine api call, without needing to do lookups of the VM Name to VM ID would be so beneficial and easy for end-use.

I wish I knew Ruby ...  I only know a little bit of Python.  I certainly wish I could help with the coding ..

-dave

**Comment by niwo** [comment]
Hi Dave,

I implemented a update function for vm's in v1.3.3 as you suggested, see:

    cloudstack-cli vm help update

I hope this is useful to you.

Cheers,
Nik
