### ISSUE TITLE
cs iso detach VM_ID

### ISSUE THREAD

**Issue by sdrose** [niwo/cloudstack-cli#9]
Hello!
I am looking at the cs iso detach command, and I see it requests a VM_ID.  I know other commands in the cloudstack_cli use a resolver from VM name to VM_ID.  I am wondering if you would like that same functionality in this portion of your software?

You have created Excellent software!!!!  

Thank you! 
-dave

**Comment by niwo** [comment]
Hi Dave

Sure that would be a good improvement.
I'm off the next days, but I will have a look at the things you reported as.

Cheers,
Nik

**Comment by niwo** [comment]
Hi Dave,

Improved in f553bcb2f86783afe7720f781c969c12ba799f22 (v1.3.0).
Thanks for reporting!

Nik
